@startuml
class Identite{
 - nip : String
 - nom : String
 - prenom : String
}


class Etudiant{
 - identite : Identite
 - formation : Formation
 - resultat : HashMap

 + moyenneNote() : double
}


class Formation{
 - identifiant : String
 - matieres : HashMap<String,double>
}


class GroupeEtudiant{
 - etudiants : ArrayList
 - formation : Formation
 + moyenneNote(String matiere) : double
}


Etudiant "1"->"1" GroupeEtudiant : -contient
Formation "1"->"1" GroupeEtudiant : -contient
Identite "1"->"1" Etudiant : -contient
Formation "1"->"1" Etudiant : -contient
@enduml